### ISSUE TITLE
Disable the polyfill when the feature is available in ember-source

### ISSUE THREAD

**Issue by Windvis** [Windvis/ember-router-service-refresh-polyfill#1]
Once the [upstream PR](https://github.com/emberjs/ember.js/pull/19471#pullrequestreview-616899946) is merged we know the version for which the polyfill needs to be disabled.

The polyfill should be removed from the final build of all projects that have this version and a warning should be shown in the console that the polyfill can be safely removed.

**Comment by musaffa** [comment]
Also consider moving it to [ember-polyfills](https://github.com/ember-polyfills).

**Comment by Windvis** [comment]
@musaffa Yes, for sure! Once the PR is merged I will finish up this addon and ask around to get it moved to the ember-polyfill organisation.
