### ISSUE TITLE
Configure CI to release new versions when pushing tags

### ISSUE THREAD

**Issue by Windvis** [Windvis/ember-router-service-refresh-polyfill#18]
This would allow anyone with tag pushing rights to release new versions without having to have npm permissions.

More information about the potential setup: https://discord.com/channels/480462759797063690/525367494400278538/967111203333734441
Another option from the Github Docs: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages#publishing-packages-using-yarn

**Comment by ctjhoa** [comment]
This is how I do it on my repos
https://github.com/concordnow/ember-aria-tabs/blob/master/.github/workflows/main.yml#L105
I use `release-it` to create the tag, bump package.json (w/ lockfile) and update changelog.
CI is in charge of the publishing part.
